### ISSUE TITLE
Bioconductor binary reports directory of lock file does not exist in /Users/biocbuild

### ISSUE THREAD

**Issue by jwokaty** [ArtifactDB/gypsum-R#4]
When the Bioconductor binary for gypsum is installed on a mac, it expects the cache to be along the `/Users/biocbuild` path, which is a user on the build machine. We think this is due to the way that `cacheDirectory` was written to prevent re-evaluating.  We think the issue might also be exist for someone installing a Windows binary, but I have not checked it yet. There isn't an issue if someone installs from source. Here's an example:

```
> BiocManager::install("gypsum")
Bioconductor version 3.19 (BiocManager 1.30.22), R Under development (unstable)
  (2024-03-04 r86048)
Installing package(s) 'gypsum'
trying URL 'https://bioconductor.org/packages/3.19/bioc/bin/macosx/big-sur-x86_64/contrib/4.4/gypsum_0.99.10.tgz'
Content type 'application/x-gzip' length 400567 bytes (391 KB)
==================================================
downloaded 391 KB


The downloaded binary packages are in
	/var/folders/f3/trs0_sy90vvfhr807w3vr2zr0000gr/T//Rtmp0MRDyy/downloaded_packages
Old packages: 'rmarkdown', 'scRNAseq'
> library(gypsum)
> listAssets("test-R")
Error in lock(paste0(config.path, ".LOCK")) : 
  Directory of lock file does not exist: '/Users/biocbuild/Library/Caches/org.R-project.R/R/gypsum/credentials'
In addition: Warning message:
In normalizePath(dn) :
  path[1]="/Users/biocbuild/Library/Caches/org.R-project.R/R/gypsum/credentials": No such file or directory
> sessionInfo()
R Under development (unstable) (2024-03-04 r86048)
Platform: x86_64-apple-darwin20
Running under: macOS Big Sur 11.7.10

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRblas.0.dylib 
LAPACK: /Library/Frameworks/R.framework/Versions/4.4-x86_64/Resources/lib/libRlapack.dylib;  LAPACK version 3.12.0

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

time zone: America/New_York
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gypsum_0.99.10

loaded via a namespace (and not attached):
 [1] digest_0.6.34       R6_2.5.1            base64enc_0.1-3    
 [4] magrittr_2.0.3      rappdirs_0.3.3      glue_1.7.0         
 [7] filelock_1.0.3      aws.signature_0.6.0 parallel_4.4.0     
[10] lifecycle_1.0.4     xml2_1.3.6          cli_3.6.2          
[13] aws.s3_0.3.21       compiler_4.4.0      httr_1.4.7         
[16] tools_4.4.0         curl_5.2.1          httr2_1.0.0        
[19] BiocManager_1.30.22 jsonlite_1.8.8      rlang_1.1.3
```

**Comment by hpages** [comment]
There's actually an issue when someone installs from source: environment variable `GYPSUM_CACHE_DIR` will be ignored if it's set (or its value gets changed) after the fact:
```
> cacheDirectory()
[1] "/home/hpages/.cache/R/gypsum"

> Sys.setenv(GYPSUM_CACHE_DIR="titi")

> cacheDirectory()
[1] "/home/hpages/.cache/R/gypsum"
```
To actually see a change in the returned value, one needs to reinstall the package!

The root cause of this is the same as for the issue reported by Jen above, which is that the path returned by `cacheDirectory()` is pre-computed once for all at installation time (or at binary creation time).

**Comment by LTLA** [comment]
Oops.  The install-time phenomenon is fixed in 0.99.13.

The behavior of the environment variable is a different issue. Currently I think it's desirable as I only want the environment variable to affect the initial value before any call to `cacheDirectory()`; I don't want subsequent changes to the environment variable to override an explicit user setter call to `cacheDirectory()`. The current behavior is probably reasonable as these environment variables are usually set before R start-up and most people don't change them in the middle of the session.

**Comment by hpages** [comment]
Sounds good. As long as people don't need to reinstall **gypsum** after they set `GYPSUM_CACHE_DIR`.

**Comment by hpages** [comment]
@jwokaty @vjcitn Can any of you check that the new **gypsum** binaries (Mac & Windows) work properly, and close this?
Thanks

**Comment by jwokaty** [comment]
I can confirm that after installing the new binaries on Windows and Mac, the `cacheDirectory()` lists a user directory, not biocbuild.
